image: python:2.7-alpine

pages:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - pelican -s publishconf.py
    - pelican-themes --install Casper2Pelican/
    - mkdir .public
    - cp -r output/* .public
    - mv .public public
  artifacts:
    paths:
    - public
